version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: tomabot-postgres
    environment:
      POSTGRES_DB: tomabot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: c6VgHI63d
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tomabot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tomabot"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tomabot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tomabot-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: tomabot-adminer
    ports:
      - "8181:8181"
    networks:
      - tomabot-network
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  tomabot-network:
    driver: bridge