spring:
  application:
    name: tomabot

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  quartz:
    job-store-type: jdbc
    auto-startup: true
    wait-for-jobs-to-complete-on-shutdown: true
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: TomaBot
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 20000
            dataSource: myDataSource
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
          dataSource:
            myDataSource:
              provider: hikaricp
              URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
              user: ${DB_USER}
              password: ${DB_PASSWORD}
              driver: org.postgresql.Driver

  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: "tomabot-scheduler-"

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}
    activity: "🍅 /start to focus"
    status: ONLINE

tomabot:
  pomodoro:
    default-focus-duration: 25
    default-short-break: 5
    default-long-break: 15
    long-break-interval: 4

  limits:
    freemium:
      max-tasks: 5
      stats-history-days: 7
    premium:
      max-tasks: -1
      stats-history-days: -1

  stats:
    cache-ttl-minutes: 5
    aggregation-enabled: true
    daily-aggregation-cron: "0 5 0 * * *"  # 00:05 AM daily
    streak-check-cron: "0 0 * * * *"       # Every hour
    weekly-cleanup-cron: "0 0 1 * * SUN"   # 01:00 AM Sunday

    leaderboard:
      top-users-count: 100
      cache-ttl-hours: 1
      display-limit: 10
      refresh-cron: "0 0 * * * *"            # Every hour
      cleanup-cron: "0 0 0 * * *"            # Daily at midnight
      enabled-types:
        - LEVEL
        - XP
        - SESSIONS
        - FOCUS_TIME
        - STREAK
        - TASKS
        - ACHIEVEMENTS

  timezone:
    default: UTC

logging:
  level:
    root: INFO
    com.tomabot: DEBUG
    net.dv8tion.jda: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true

logging:
  level:
    com.tomabot: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.tomabot: INFO